#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

// Load custom helpers before Composer to allow overriding...
require __DIR__.'/app/Http/Helpers.php';

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__.'/bootstrap/app.php')
    ->handleCommand(new Symfony\Component\Console\Input\ArgvInput);

exit($status);
