<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use App\Models\Permission;

class InsertPermissions extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $permissions = [

            [
                "identifier" => "admin.home.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "الرئيسية"],
                "en" => ["name" => "home"],
            ],
            [
                "identifier" => "admin.settings.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض اﻹعدادات"],
                "en" => ["name" => "List of settings"],
            ],
            [
                "identifier" => "admin.settings.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل اﻻعدادات"],
                "en" => ["name" => "Update of settings"],
            ],
            [
                "identifier" => "admin.activities.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض الأنشطة"],
                "en" => ["name" => "list of activities"],
            ],
            [
                "identifier" => "admin.activities.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء نشاط جديد"],
                "en" => ["name" => "create new activity"],
            ],
            [
                "identifier" => "admin.activities.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل النشاط"],
                "en" => ["name" => "update of activity"],
            ],
            [
                "identifier" => "admin.activities.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف النشاط"],
                "en" => ["name" => "delete of activity"],
            ],
            [
                "identifier" => "admin.branches.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض الفروع"],
                "en" => ["name" => "list of branches"],
            ],
            [
                "identifier" => "admin.branches.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء فرع جديد"],
                "en" => ["name" => "create new branche"],
            ],
            [
                "identifier" => "admin.branches.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل الفرع"],
                "en" => ["name" => "update of branche"],
            ],
            [
                "identifier" => "admin.branches.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف الفرع"],
                "en" => ["name" => "delete of branche"],
            ],
            [
                "identifier" => "admin.branch.products.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض منتجات الفرع"],
                "en" => ["name" => "list of branche products"],
            ],
            [
                "identifier" => "admin.branch.products.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء منتج فرع جديد"],
                "en" => ["name" => "create new branche product"],
            ],
            [
                "identifier" => "admin.branch.products.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل منتج فرع"],
                "en" => ["name" => "update of branche product"],
            ],
            [
                "identifier" => "admin.branch.products.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف منتج فرع"],
                "en" => ["name" => "delete of branche product"],
            ],
            [
                "identifier" => "admin.branch.zones",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض مناطق الفرع"],
                "en" => ["name" => "list of branche zones"],
            ],
            [
                "identifier" => "admin.branch.zones.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء منطقة فرع جديدة"],
                "en" => ["name" => "create new branche zone"],
            ],
            [
                "identifier" => "admin.branch.zones.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل منطقة فرع"],
                "en" => ["name" => "update of branche zone"],
            ],
            [
                "identifier" => "admin.branch.zones.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف منطقة فرع"],
                "en" => ["name" => "delete of branche zone"],
            ],
            [
                "identifier" => "admin.categories.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض المنتجات"],
                "en" => ["name" => "list of categories"],
            ],
            [
                "identifier" => "admin.categories.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء فئة جديده"],
                "en" => ["name" => "create new category"],
            ],
            [
                "identifier" => "admin.categories.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل الفئة"],
                "en" => ["name" => "update of category"],
            ],
            [
                "identifier" => "admin.categories.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف الفئة"],
                "en" => ["name" => "delete of category"],
            ],
            [
                "identifier" => "admin.categories.show",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "رؤية الأقسام الفرعيه"],
                "en" => ["name" => "show sub of category"],
            ],
            [
                "identifier" => "admin.groups.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض المجموعات"],
                "en" => ["name" => "list of groups"],
            ],
            [
                "identifier" => "admin.groups.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء مجموعة جديده"],
                "en" => ["name" => "create new group"],
            ],
            [
                "identifier" => "admin.groups.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل المجموعة"],
                "en" => ["name" => "update of group"],
            ],
            [
                "identifier" => "admin.groups.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف المجموعة"],
                "en" => ["name" => "delete of group"],
            ],
            [
                "identifier" => "admin.group.permissions.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض مجموعة الصلاحيات"],
                "en" => ["name" => "list of group permissions"],
            ],
            [
                "identifier" => "admin.group.permissions.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء مجموعة الصلاحيات جديده"],
                "en" => ["name" => "create new group permissions"],
            ],
            [
                "identifier" => "admin.group.permissions.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل مجموعة الصلاحيات"],
                "en" => ["name" => "update of group permissions"],
            ],
            [
                "identifier" => "admin.group.permissions.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف مجموعة الصلاحيات"],
                "en" => ["name" => "delete of group permissions"],
            ],
            [
                "identifier" => "admin.locations.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض اﻷماكن"],
                "en" => ["name" => "list of locations"],
            ],
            [
                "identifier" => "admin.locations.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء مكان جديد"],
                "en" => ["name" => "create new location"],
            ],
            [
                "identifier" => "admin.locations.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل المكان"],
                "en" => ["name" => "update of location"],
            ],
            [
                "identifier" => "admin.locations.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف المكان"],
                "en" => ["name" => "delete of location"],
            ],
            [
                "identifier" => "admin.orders.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض الطلبات"],
                "en" => ["name" => "list of orders"],
            ],
            [
                "identifier" => "admin.orders.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء طلب جديد"],
                "en" => ["name" => "create new order"],
            ],
            [
                "identifier" => "admin.orders.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل الطلب"],
                "en" => ["name" => "update of order"],
            ],
            [
                "identifier" => "admin.orders.show",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تفاصيل الطلبات"],
                "en" => ["name" => "orders details"],
            ],
            [
                "identifier" => "admin.orders.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف الطلب"],
                "en" => ["name" => "delete of order"],
            ],
            [
                "identifier" => "admin.order.products",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض منتجات الطلب"],
                "en" => ["name" => "list of order products"],
            ],
            [
                "identifier" => "admin.order.products.add",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء منتج طلب جديد"],
                "en" => ["name" => "create new order products"],
            ],
            [
                "identifier" => "admin.order.products.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل منتج طلب"],
                "en" => ["name" => "update of order products"],
            ],
            [
                "identifier" => "admin.order.products.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف منتج طلب"],
                "en" => ["name" => "delete of order products"],
            ],
            [
                "identifier" => "admin.permissions.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض الصلحيات"],
                "en" => ["name" => "list of permissions"],
            ],
            [
                "identifier" => "admin.permissions.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل الصالحية"],
                "en" => ["name" => "update of permission"],
            ],
            [
                "identifier" => "admin.products.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض المنتجات"],
                "en" => ["name" => "list of products"],
            ],
            [
                "identifier" => "admin.products.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء منتج جديد"],
                "en" => ["name" => "create new product"],
            ],
            [
                "identifier" => "admin.products.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل المنتج"],
                "en" => ["name" => "update of product"],
            ],
            [
                "identifier" => "admin.products.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف المنتج"],
                "en" => ["name" => "delete of product"],
            ],
            [
                "identifier" => "admin.product.image.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف صوره المنتج"],
                "en" => ["name" => "delete of product image"],
            ],
            [
                "identifier" => "admin.stocks.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض المخازن"],
                "en" => ["name" => "list of stocks"],
            ],
            [
                "identifier" => "admin.stocks.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء مخزن جديد"],
                "en" => ["name" => "create new stock"],
            ],
            [
                "identifier" => "admin.subscribers.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض المشتركين فى النشره البريدية"],
                "en" => ["name" => "list of subscribers"],
            ],
            [
                "identifier" => "admin.subscribers.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء المشترك فى النشره البريدية جديد"],
                "en" => ["name" => "create new subscriber"],
            ],
            [
                "identifier" => "admin.subscribers.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل المشترك فى النشره البريدية"],
                "en" => ["name" => "update of subscriber"],
            ],
            [
                "identifier" => "admin.subscribers.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف المشترك فى النشره البريدية"],
                "en" => ["name" => "delete of subscriber"],
            ],
            [
                "identifier" => "admin.tickets.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض الشكاوى"],
                "en" => ["name" => "list of tickets"],
            ],
            [
                "identifier" => "admin.tickets.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء الشكوى"],
                "en" => ["name" => "create new ticket"],
            ],
            [
                "identifier" => "admin.tickets.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل الشكوى"],
                "en" => ["name" => "update of ticket"],
            ],
            [
                "identifier" => "admin.tickets.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف الشكوى"],
                "en" => ["name" => "delete of ticket"],
            ],
            [
                "identifier" => "admin.units.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض الوحدات"],
                "en" => ["name" => "list of units"],
            ],
            [
                "identifier" => "admin.units.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء وحدة جديده"],
                "en" => ["name" => "create new unit"],
            ],
            [
                "identifier" => "admin.units.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل اتلوحدة"],
                "en" => ["name" => "update of unit"],
            ],
            [
                "identifier" => "admin.units.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف الوحدة"],
                "en" => ["name" => "delete of unit"],
            ],
            [
                "identifier" => "admin.users.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض المستخدمين"],
                "en" => ["name" => "list of users"],
            ],
            [
                "identifier" => "admin.users.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء مستخدم جديد"],
                "en" => ["name" => "create new user"],
            ],
            [
                "identifier" => "admin.users.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل المستخدم"],
                "en" => ["name" => "update of user"],
            ],
            [
                "identifier" => "admin.users.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف المستخدم"],
                "en" => ["name" => "delete of user"],
            ],
            [
                "identifier" => "admin.user.addresses.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض عناوين المستخدم"],
                "en" => ["name" => "list of user addresses"],
            ],
            [
                "identifier" => "admin.user.addresses.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء عنوان مستخدم جديد"],
                "en" => ["name" => "create new user address"],
            ],
            [
                "identifier" => "admin.user.addresses.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل عنوان مستخدم"],
                "en" => ["name" => "update of user address"],
            ],
            [
                "identifier" => "admin.user.addresses.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف عنوان مستخدم"],
                "en" => ["name" => "delete of user address"],
            ],
            [
                "identifier" => "admin.user.devices.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض أجهزة المستخدم"],
                "en" => ["name" => "list of user devices"],
            ],
            [
                "identifier" => "admin.user.devices.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء جهاز مستخدم جديد"],
                "en" => ["name" => "create new user device"],
            ],
            [
                "identifier" => "admin.user.devices.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف جهاز المستخدم"],
                "en" => ["name" => "delete of user device"],
            ],
            [
                "identifier" => "admin.users.groups.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل مجموعات المستخدم"],
                "en" => ["name" => "update user groups"],
            ],
            [
                "identifier" => "admin.vehicles.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض المركبات"],
                "en" => ["name" => "list of vehicles"],
            ],
            [
                "identifier" => "admin.vehicles.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء مركبة جديد"],
                "en" => ["name" => "create new vehicle"],
            ],
            [
                "identifier" => "admin.vehicles.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل المركبة"],
                "en" => ["name" => "update of vehicle"],
            ],
            [
                "identifier" => "admin.vehicles.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف المركبة"],
                "en" => ["name" => "delete of vehicle"],
            ],
            [
                "identifier" => "admin.vendors.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض البائعين"],
                "en" => ["name" => "list of vendors"],
            ],
            [
                "identifier" => "admin.vendors.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء بائع جديد"],
                "en" => ["name" => "create new vendors"],
            ],
            [
                "identifier" => "admin.vendors.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل البائع"],
                "en" => ["name" => "update of vendor"],
            ],
            [
                "identifier" => "admin.vendors.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف البائع"],
                "en" => ["name" => "delete of vendor"],
            ],
            [
                "identifier" => "admin.vendor.reviews.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض التعليقات"],
                "en" => ["name" => "list of vendor reviews"],
            ],
            [
                "identifier" => "admin.vendor.reviews.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء تعليق جديد"],
                "en" => ["name" => "create new vendor review"],
            ],
            [
                "identifier" => "admin.vendor.reviews.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل التعليق"],
                "en" => ["name" => "update of vendor review"],
            ],
            [
                "identifier" => "admin.vendor.reviews.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف التعليق"],
                "en" => ["name" => "delete of vendor review"],
            ],
            [
                "identifier" => "admin.subscribes.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض المرسلات"],
                "en" => ["name" => "list of subscribes"],
            ],
            [
                "identifier" => "admin.subscribes.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "ارسال بريد جديد"],
                "en" => ["name" => "create new subscribe"],
            ],
            [
                "identifier" => "admin.actual_shipments.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض الشحنات الفعلية"],
                "en" => ["name" => "list of actual shipments"],
            ],
            [
                "identifier" => "admin.actual_shipments.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء الشحنات الفعلية"],
                "en" => ["name" => "create new actual shipment"],
            ],
            [
                "identifier" => "admin.actual_shipments.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل الشحنات الفعلية"],
                "en" => ["name" => "update of actual shipment"],
            ],
            [
                "identifier" => "admin.actual_shipments.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف الشحنات الفعلية"],
                "en" => ["name" => "delete of actual shipment"],
            ],
            [
                "identifier" => "vendor.branch.products.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض منتجات فرع بائع"],
                "en" => ["name" => "list of vendor branch products"],
            ],
            [
                "identifier" => "vendor.branch.products.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "اضافة منتج فرع بائع"],
                "en" => ["name" => "create new vendor branch product"],
            ],
            [
                "identifier" => "vendor.branch.products.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل منتج فرع بائع"],
                "en" => ["name" => "update of vendor branch product"],
            ],
            [
                "identifier" => "vendor.branch.products.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف منتج فرع بائع"],
                "en" => ["name" => "delete of vendor branch product"],
            ],
            [
                "identifier" => "admin.vouchers.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض القسائم"],
                "en" => ["name" => "list of vouchers"],
            ],
            [
                "identifier" => "admin.vouchers.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء قسيمة جديد"],
                "en" => ["name" => "create new voucher"],
            ],
            [
                "identifier" => "admin.vouchers.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل القسيمة"],
                "en" => ["name" => "update of voucher"],
            ],
            [
                "identifier" => "admin.vouchers.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف القسيمة"],
                "en" => ["name" => "delete of voucher"],
            ],
            [
                "identifier" => "admin.vouchers.list",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تفاصيل القسيمة"],
                "en" => ["name" => "Voucher details list"],
            ],
            [
                "identifier" => "admin.segmentation.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض التقسيمات"],
                "en" => ["name" => "list of segmentation"],
            ],
            [
                "identifier" => "admin.segmentation.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء تقسيم جديد"],
                "en" => ["name" => "create new segmentation"],
            ],
            [
                "identifier" => "admin.segmentation.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل التقسيم"],
                "en" => ["name" => "update of segmentation"],
            ],
            [
                "identifier" => "admin.segmentation.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف التقسيم"],
                "en" => ["name" => "delete of segmentation"],
            ],
            [
                "identifier" => "admin.companies.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض الشركات"],
                "en" => ["name" => "list of Companies"],
            ],
            [
                "identifier" => "admin.companies.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء شركة جديد"],
                "en" => ["name" => "create new company"],
            ],
            [
                "identifier" => "admin.companies.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل الشركة"],
                "en" => ["name" => "update of company"],
            ],
            [
                "identifier" => "admin.companies.destroy",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "حذف الشركة" ],
                "en" => [ "name" => "delete of company" ],
            ],
            [
                "identifier" => "admin.transactions.index",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "عرض العاملات" ],
                "en" => [ "name" => "list of transactions" ],
            ],
            [
                "identifier" => "admin.transactions.create",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "انشاء معاملة جديد" ],
                "en" => [ "name" => "create new transaction" ],
            ],
            [
                "identifier" => "admin.shipments.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض رحله"],
                "en" => ["name" => "list of  shipment"],
            ],
            [
                "identifier" => "admin.shipments.create",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "انشاء رحله"],
                "en" => ["name" => "create new  shipment"],
            ],
            [
                "identifier" => "admin.shipments.update",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "تعديل رحله"],
                "en" => ["name" => "update of shipment"],
            ],
            [
                "identifier" => "admin.shipments.destroy",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "حذف رحله"],
                "en" => ["name" => "delete of shipment"],
            ],
            [
                "identifier" => "admin.payments.index",
                "active" => true,
                "type" => 0,
                "ar" => ["name" => "عرض المدفوعات"],
                "en" => ["name" => "list of payments"],
            ],
            [
                "identifier" => "admin.payments.create",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "انشاء دفع جديد" ],
                "en" => [ "name" => "create new payment" ],
            ],
            [
                "identifier" => "admin.banners.index",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "عرض لافتات" ],
                "en" => [ "name" => "list of banner" ],
            ],
            [
                "identifier" => "admin.banners.create",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "انشاء لافتات جديد" ],
                "en" => [ "name" => "create new banner" ],
            ],
            [
                "identifier" => "admin.banners.update",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "تعديل لافتات" ],
                "en" => [ "name" => "update of banner" ],
            ],
            [
                "identifier" => "admin.banners.destroy",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "حذف لافتات" ],
                "en" => [ "name" => "delete of banner" ],
            ],
            [
                "identifier" => "admin.coupons.index",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "عرض كوبون" ],
                "en" => [ "name" => "list of Coupon" ],
            ],
            [
                "identifier" => "admin.coupons.create",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "انشاء كوبون جديد" ],
                "en" => [ "name" => "create new Coupon" ],
            ],
            [
                "identifier" => "admin.coupons.update",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "تعديل كوبون" ],
                "en" => [ "name" => "update of Coupon" ],
            ],
            [
                "identifier" => "admin.coupons.destroy",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "حذف كوبون" ],
                "en" => [ "name" => "delete of Coupon" ],
            ],
            [
                "identifier" => "admin.discounts.index",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "عرض الخصومات" ],
                "en" => [ "name" => "list of discount" ],
            ],
            [
                "identifier" => "admin.discounts.create",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "انشاء الخصومات جديد" ],
                "en" => [ "name" => "create new discount" ],
            ],
            [
                "identifier" => "admin.discounts.update",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "تعديل الخصومات" ],
                "en" => [ "name" => "update of discount" ],
            ],
            [
                "identifier" => "admin.discounts.destroy",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "حذف الخصومات" ],
                "en" => [ "name" => "delete of discount" ],
            ],
            [
                "identifier" => "admin.logs.index",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "عرض سجلات" ],
                "en" => [ "name" => "list of logs" ],
            ],
            [
                "identifier" => "vendor.staff.update",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "تعديل الموظفين" ],
                "en" => [ "name" => "Edit Staff" ],
            ],
            [
                "identifier" => "vendor.staff.destroy",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "مسح الموظفين" ],
                "en" => [ "name" => "Delete Staff" ],
            ],
            [
                "identifier" => "vendor.staff.create",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "انشاء موظف جديد" ],
                "en" => [ "name" => "Create Staff" ],
            ],
            [
                "identifier" => "vendor.staff.index",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "عرض الموظفين" ],
                "en" => [ "name" => "List Staff" ],
            ],
            [
                "identifier" => "vendor.orders.update",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "تعديل الطلبات" ],
                "en" => [ "name" => "Edit Orders" ],
            ],
            [
                "identifier" => "vendor.orders.destroy",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "مسح الطلبات" ],
                "en" => [ "name" => "Delete Orders" ],
            ],
            [
                "identifier" => "vendor.orders.create",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "انشاء طلبات جديدة" ],
                "en" => [ "name" => "Create Orders" ],
            ],
            [
                "identifier" => "vendor.orders.index",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "عرض الطلبات" ],
                "en" => [ "name" => "List Orders" ],
            ],
            [
                "identifier" => "vendor.order.products.update",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "تعديل منتجات الطلب" ],
                "en" => [ "name" => "Edit order products" ],
            ],
            [
                "identifier" => "vendor.order.products.destroy",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "مسح منتجات الطلب" ],
                "en" => [ "name" => "Delete order products" ],
            ],
            [
                "identifier" => "vendor.order.products.create",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "انشاء منتجات جديدة للطلبات" ],
                "en" => [ "name" => "Create order products" ],
            ],
            [
                "identifier" => "vendor.order.products.index",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "عرض منتجات الطلبات" ],
                "en" => [ "name" => "List order products" ],
            ],
            [
                "identifier" => "vendor.branches.update",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "تعديل اﻷفروع" ],
                "en" => [ "name" => "Edit branches" ],
            ],
            [
                "identifier" => "vendor.branches.destroy",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "مسح اﻻفروع" ],
                "en" => [ "name" => "Delete branch" ],
            ],
            [
                "identifier" => "vendor.branches.create",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "انشاء فرع جديد" ],
                "en" => [ "name" => "Create branch" ],
            ],
            [
                "identifier" => "vendor.branches.index",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "عرض الأفروع" ],
                "en" => [ "name" => "List branches" ],
            ],
            [
                "identifier" => "vendor.branch.products.update",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "تعديل منتجات الفرع" ],
                "en" => [ "name" => "Branch products update" ],
            ],
            [
                "identifier" => "vendor.branch.products.destroy",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "مسح منتجات الفرع" ],
                "en" => [ "name" => "Delete branch products" ],
            ],
            [
                "identifier" => "vendor.branch.products.create",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "انشاء منتجات جديدة للفرع" ],
                "en" => [ "name" => "Create branch products" ],
            ],
            [
                "identifier" => "vendor.branch.products.index",
                "active" => true,
                "type" => 1,
                "ar" => [ "name" => "عرض منتجات الفرع" ],
                "en" => [ "name" => "List branch products" ],
            ],
            [
                "identifier" => "admin.shippingCompanies.index",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "عرض شركات الشحن" ],
                "en" => [ "name" => "list of shipping Companies" ],
            ],
            [
                "identifier" => "admin.shippingCompanies.create",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "انشاء شركة شحن جديد" ],
                "en" => [ "name" => "create new shipping company" ],
            ],
            [
                "identifier" => "admin.shippingCompanies.update",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "تعديل شركة الشحن" ],
                "en" => [ "name" => "update of shipping company" ],
            ],
            [
                "identifier" => "admin.shippingCompanies.destroy",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "حذف شركة الشحن" ],
                "en" => [ "name" => "delete of shipping company" ],
            ],
            [
                "identifier" => "admin.revenues.index",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "عرض اﻹيرادات" ],
                "en" => [ "name" => "list of revenues" ],
            ],
            [
                "identifier" => "admin.vendors.settle",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "تسوية حساب البائع" ],
                "en" => [ "name" => "Vendor settle" ],
            ],
            [
                "identifier" => "admin.users.settle",
                "active" => true,
                "type" => 0,
                "ar" => [ "name" => "تسوية حساب السائق" ],
                "en" => [ "name" => "Driver settle" ],
            ],
        ];

        foreach ($permissions as $permission) {
            $permissionObj = new Permission($permission);
            $permissionObj->identifier = $permission['identifier'];
            $permissionObj->save();
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
